# Generated by Django 2.2.2 on 2019-06-20 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaModel',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereco')),
                ('cliente_cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('cliente_rg', models.CharField(default=0, max_length=9, verbose_name='RG')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['cliente_nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoModel',
            fields=[
                ('venda_id', models.AutoField(primary_key=True, serialize=False)),
                ('venda_data', models.DateField(default=datetime.datetime(2019, 7, 20, 15, 30, 4, 971732), verbose_name='Data Venda')),
                ('valor_total_venda', models.FloatField(max_length=20, null=True, verbose_name='Valor total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.PessoaModel')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['venda_id'],
            },
        ),
    ]
